services:

  gateway:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - back
      - back-predict 
      - back-predict1      

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - PREDICT_SERVICE_URL=http://back-predict:5000
      - PREDICT1_SERVICE_URL=http://back-predict1:5001
    restart: unless-stopped
    depends_on:
      - back-predict
      - back-predict1

  back-predict:
    build:
      context: ./back-predict
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: unless-stopped
    
  back-predict1:
    build:
      context: ./back-predict1
      dockerfile: Dockerfile
    expose:
      - "5001"
    restart: unless-stopped    

volumes:
  caddy_data:    