services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - back-predict
    environment:
      - PREDICT_SERVICE_URL=http://back-predict:5000
    restart: unless-stopped

  back-predict:
    build:
      context: ./back-predict
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
