DROP TABLE IF EXISTS events;
CREATE TABLE events (
    id SERIAL PRIMARY KEY,
    event_date TIMESTAMP,
    location TEXT,
    name TEXT,
    participation_type TEXT,
    popularity_score INTEGER,
    sport_type TEXT
);

insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/04/2025 04:05 PM', 'Arena G', 'World Contest', 'Participant', 19, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/30/2025 02:00 AM', 'Pool D', 'Enthusiasts', 'Participant', 28, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/09/2025 11:04 PM', 'Palais des Congrès', 'Course', 'Participant', 73, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/08/2025 11:29 AM', 'Arena B', 'Tournament', 'Participant', 67, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/27/2025 01:26 PM', 'Stadium A', 'Showcase', 'Spectator', 87, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/11/2025 05:58 AM', 'Court E', 'Course', 'Spectator', 1, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/22/2025 07:46 AM', 'Arena B', 'Enthusiasts', 'Participant', 20, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/10/2025 01:50 AM', 'Arena G', 'Enthusiasts', 'Spectator', 64, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/12/2025 11:10 AM', 'Arena B', 'Morning Gala', 'Spectator', 11, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/06/2025 06:43 AM', 'Stadium A', 'Tournament', 'Spectator', 76, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/05/2025 09:19 AM', 'Arena G', 'Splash', 'Participant', 17, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/03/2025 10:29 PM', 'Accor Arena', 'World Contest', 'Participant', 74, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/06/2025 10:26 PM', 'Cnit', 'Fantasy 2025', 'Participant', 100, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/13/2025 04:39 PM', 'Zenith', 'Fantasy 2025', 'Spectator', 38, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/10/2025 05:39 PM', 'Accor Arena', 'Extravaganza', 'Participant', 36, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/15/2025 08:02 AM', 'Cnit', 'Epic Battle', 'Spectator', 93, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/20/2025 05:44 PM', 'Parc des princes', 'European Step', 'Spectator', 47, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/03/2025 11:00 PM', 'Parc des princes', 'Amazing stuff', 'Spectator', 24, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/11/2025 02:46 PM', 'Accor Arena', 'Morning Gala', 'Spectator', 13, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/20/2025 11:01 AM', 'Stadium F', 'Showcase', 'Spectator', 56, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/09/2025 03:36 PM', 'Stadium F', 'Enthusiasts', 'Participant', 0, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/06/2025 04:53 AM', 'Stade de France', 'Tournament', 'Spectator', 25, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/11/2025 12:10 PM', 'Arena B', 'Course', 'Participant', 56, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/10/2025 04:50 AM', 'Cnit', 'Fantasy 2025', 'Spectator', 83, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/12/2025 08:59 AM', 'Cnit', 'Cool Training 2025', 'Spectator', 4, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/13/2025 12:02 PM', 'Arena G', 'Amazing stuff', 'Spectator', 77, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/05/2025 08:33 PM', 'Palais des Congrès', 'Course', 'Spectator', 55, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/05/2025 09:35 PM', 'Stadium A', 'Tournament', 'Participant', 82, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/07/2025 07:59 AM', 'Pool D', 'Tournament', 'Participant', 63, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/10/2025 03:12 AM', 'Arena B', 'Morning Gala', 'Spectator', 11, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 03:45 AM', 'Palais des Congrès', 'Cool Training 2025', 'Spectator', 26, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/02/2025 10:13 PM', 'Parc des princes', 'Fantasy 2025', 'Participant', 5, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 04:39 AM', 'Palais des Congrès', 'Fantasy 2025', 'Participant', 6, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/01/2025 08:17 PM', 'Zenith', 'European Step', 'Participant', 71, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/08/2025 12:47 PM', 'Stadium F', 'European Step', 'Spectator', 41, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/27/2025 03:03 AM', 'Stade de France', 'Amazing stuff', 'Spectator', 69, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/17/2025 10:09 AM', 'Arena B', 'Course', 'Participant', 34, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/18/2025 02:04 PM', 'Parc des princes', 'Tournament', 'Spectator', 68, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/25/2025 10:47 AM', 'Accor Arena', 'World Contest', 'Participant', 37, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/23/2025 04:23 PM', 'Zenith', 'Cool Training 2025', 'Participant', 33, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/10/2025 08:11 PM', 'Park C', 'Tournament', 'Participant', 97, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/17/2025 03:25 AM', 'Stadium F', 'Best University', 'Spectator', 84, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/05/2025 11:43 PM', 'Palais des Congrès', 'Extravaganza', 'Spectator', 13, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/24/2025 01:57 AM', 'Cnit', 'Tournament', 'Spectator', 96, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/14/2025 11:23 PM', 'Court E', 'Splash', 'Participant', 21, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 04:00 PM', 'Stadium A', 'World Contest', 'Participant', 70, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/11/2025 12:51 AM', 'Court E', 'Splash', 'Participant', 26, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/30/2025 09:47 AM', 'Palais des Congrès', 'World Contest', 'Spectator', 16, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/03/2025 10:34 AM', 'Arena B', 'Tournament', 'Spectator', 11, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/02/2025 11:04 AM', 'Pool D', 'Epic Battle', 'Spectator', 44, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/28/2025 06:10 PM', 'Stadium A', 'Splash', 'Spectator', 37, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/10/2025 11:36 PM', 'Zenith', 'Best University', 'Spectator', 73, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/17/2025 07:58 PM', 'Accor Arena', 'Splash', 'Participant', 67, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/22/2025 10:16 AM', 'Pool D', 'Fantasy 2025', 'Participant', 11, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/06/2025 06:44 AM', 'Stadium A', 'Best University', 'Spectator', 0, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/06/2025 05:26 PM', 'Arena B', 'Best University', 'Participant', 8, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/12/2025 04:14 PM', 'Park C', 'Fantasy 2025', 'Participant', 29, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/22/2025 12:20 AM', 'Parc des princes', 'Course', 'Participant', 33, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/10/2025 01:36 PM', 'Palais des Congrès', 'Enthusiasts', 'Spectator', 69, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/14/2025 03:09 PM', 'Pool D', 'Showcase', 'Participant', 34, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/06/2025 03:20 PM', 'Accor Arena', 'Showcase', 'Spectator', 60, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/18/2025 05:19 PM', 'Arena B', 'World of Experts', 'Spectator', 83, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/26/2025 05:17 AM', 'Zenith', 'World of Experts', 'Spectator', 42, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/16/2025 06:46 PM', 'Arena B', 'European Step', 'Participant', 54, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/20/2025 09:22 PM', 'Arena B', 'Tournament', 'Participant', 77, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/10/2025 04:00 PM', 'Stadium F', 'Course', 'Spectator', 49, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/05/2025 11:43 PM', 'Stadium A', 'Tournament', 'Participant', 15, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/13/2025 03:06 PM', 'Arena B', 'Cool Training 2025', 'Participant', 50, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/07/2025 09:42 PM', 'Stade de France', 'World Contest', 'Participant', 64, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/03/2025 09:42 AM', 'Parc des princes', 'Epic Battle', 'Spectator', 69, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/25/2025 05:54 PM', 'Stadium A', 'Enthusiasts', 'Participant', 28, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/02/2025 05:03 AM', 'Arena G', 'Extravaganza', 'Spectator', 25, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/29/2025 05:21 PM', 'Stade de France', 'Amazing stuff', 'Participant', 38, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/11/2025 10:31 PM', 'Stade de France', 'Epic Battle', 'Participant', 62, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/12/2025 07:06 AM', 'Park C', 'Cool Training 2025', 'Spectator', 24, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/08/2025 02:30 AM', 'Arena B', 'Showcase', 'Participant', 31, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/02/2025 08:39 PM', 'Arena B', 'Epic Battle', 'Participant', 68, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/10/2025 11:06 PM', 'Cnit', 'World of Experts', 'Participant', 88, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 04:59 AM', 'Zenith', 'Splash', 'Spectator', 61, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/16/2025 02:52 PM', 'Stade de France', 'Epic Battle', 'Participant', 14, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/13/2025 10:33 PM', 'Cnit', 'Tournament', 'Participant', 33, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/24/2025 02:46 AM', 'Palais des Congrès', 'Amazing stuff', 'Spectator', 44, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/27/2025 01:39 AM', 'Stade de France', 'World of Experts', 'Participant', 52, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/26/2025 08:22 AM', 'Pool D', 'Fantasy 2025', 'Spectator', 0, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/02/2025 09:58 PM', 'Stade de France', 'Best University', 'Spectator', 24, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/02/2025 05:22 PM', 'Stadium F', 'Tournament', 'Spectator', 3, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/12/2025 01:12 AM', 'Accor Arena', 'Fantasy 2025', 'Spectator', 26, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/16/2025 01:49 PM', 'Stade de France', 'Amazing stuff', 'Spectator', 50, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/04/2025 02:47 PM', 'Zenith', 'Fantasy 2025', 'Participant', 43, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/05/2025 01:39 AM', 'Cnit', 'Best University', 'Participant', 17, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/08/2025 02:13 AM', 'Palais des Congrès', 'Fantasy 2025', 'Participant', 1, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/10/2025 07:03 AM', 'Palais des Congrès', 'Best University', 'Spectator', 19, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/05/2025 11:29 AM', 'Stadium A', 'Fantasy 2025', 'Participant', 31, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/08/2025 04:25 PM', 'Accor Arena', 'Enthusiasts', 'Spectator', 83, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/26/2025 06:42 PM', 'Stadium A', 'World of Experts', 'Spectator', 51, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/05/2025 07:43 AM', 'Stadium F', 'European Step', 'Participant', 30, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/07/2025 08:13 PM', 'Palais des Congrès', 'World Contest', 'Participant', 27, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/05/2025 01:40 PM', 'Court E', 'Fantasy 2025', 'Spectator', 74, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/02/2025 10:50 AM', 'Palais des Congrès', 'Fantasy 2025', 'Spectator', 72, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/24/2025 05:38 PM', 'Parc des princes', 'World of Experts', 'Spectator', 69, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/08/2025 10:18 AM', 'Cnit', 'Fantasy 2025', 'Spectator', 19, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/09/2025 03:15 PM', 'Pool D', 'Cool Training 2025', 'Spectator', 56, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/12/2025 10:45 AM', 'Park C', 'Course', 'Spectator', 84, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 10:06 AM', 'Arena G', 'Amazing stuff', 'Participant', 17, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/11/2025 08:44 AM', 'Zenith', 'Enthusiasts', 'Participant', 86, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 04:39 PM', 'Arena G', 'Enthusiasts', 'Spectator', 55, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/19/2025 10:46 PM', 'Stadium A', 'Fantasy 2025', 'Spectator', 81, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/19/2025 07:33 PM', 'Pool D', 'Amazing stuff', 'Spectator', 86, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/25/2025 12:18 PM', 'Stade de France', 'Fantasy 2025', 'Participant', 54, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/14/2025 05:27 PM', 'Zenith', 'Best University', 'Participant', 57, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/08/2025 01:45 PM', 'Stade de France', 'World of Experts', 'Participant', 79, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/15/2025 06:29 PM', 'Palais des Congrès', 'Fantasy 2025', 'Spectator', 1, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/12/2025 09:51 PM', 'Palais des Congrès', 'Tournament', 'Participant', 62, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/05/2025 07:31 PM', 'Pool D', 'World Contest', 'Spectator', 94, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/07/2025 05:38 PM', 'Parc des princes', 'Fantasy 2025', 'Spectator', 20, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/01/2025 02:45 PM', 'Arena G', 'World Contest', 'Spectator', 81, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/15/2025 01:24 PM', 'Stade de France', 'Showcase', 'Spectator', 36, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/06/2025 12:50 AM', 'Arena B', 'Cool Training 2025', 'Participant', 25, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/31/2025 11:43 PM', 'Palais des Congrès', 'World Contest', 'Participant', 7, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/06/2025 01:30 AM', 'Zenith', 'Splash', 'Spectator', 63, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/16/2025 06:25 PM', 'Accor Arena', 'Course', 'Participant', 11, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/10/2025 08:23 AM', 'Stadium A', 'World Contest', 'Participant', 4, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/14/2025 02:28 PM', 'Arena B', 'Extravaganza', 'Spectator', 29, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/04/2025 09:29 AM', 'Stade de France', 'Fantasy 2025', 'Participant', 32, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/24/2025 10:14 AM', 'Stadium A', 'Best University', 'Participant', 79, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/14/2025 03:36 AM', 'Park C', 'Fantasy 2025', 'Participant', 56, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/22/2025 06:57 AM', 'Arena G', 'World of Experts', 'Participant', 63, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/09/2025 02:12 AM', 'Parc des princes', 'Cool Training 2025', 'Participant', 9, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/14/2025 05:44 PM', 'Stadium A', 'Amazing stuff', 'Participant', 51, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/13/2025 05:09 AM', 'Pool D', 'Amazing stuff', 'Spectator', 33, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/14/2025 11:27 PM', 'Cnit', 'Cool Training 2025', 'Spectator', 13, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/06/2025 03:42 PM', 'Zenith', 'Morning Gala', 'Spectator', 21, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/17/2025 05:23 AM', 'Zenith', 'Course', 'Participant', 100, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/13/2025 11:39 PM', 'Stadium A', 'Fantasy 2025', 'Spectator', 58, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/02/2025 07:13 PM', 'Zenith', 'Best University', 'Spectator', 13, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/26/2025 04:27 AM', 'Arena G', 'Showcase', 'Participant', 90, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 03:48 AM', 'Stadium F', 'Fantasy 2025', 'Spectator', 9, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/06/2025 11:58 AM', 'Stadium A', 'Showcase', 'Participant', 74, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/16/2025 03:49 PM', 'Accor Arena', 'World of Experts', 'Spectator', 1, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/13/2025 04:37 PM', 'Court E', 'Best University', 'Participant', 73, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/01/2025 08:47 AM', 'Accor Arena', 'Best University', 'Spectator', 47, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/13/2025 04:38 AM', 'Accor Arena', 'Extravaganza', 'Spectator', 76, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/17/2025 09:19 AM', 'Stade de France', 'Enthusiasts', 'Participant', 18, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/08/2025 01:54 PM', 'Accor Arena', 'European Step', 'Spectator', 55, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/21/2025 04:17 PM', 'Stadium F', 'Amazing stuff', 'Spectator', 25, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/28/2025 07:48 PM', 'Palais des Congrès', 'World Contest', 'Participant', 89, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/12/2025 02:21 AM', 'Cnit', 'European Step', 'Participant', 38, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/07/2025 06:41 AM', 'Accor Arena', 'Cool Training 2025', 'Participant', 55, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/17/2025 01:57 AM', 'Pool D', 'Splash', 'Spectator', 48, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/10/2025 05:58 AM', 'Parc des princes', 'Best University', 'Spectator', 6, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/29/2025 10:03 PM', 'Palais des Congrès', 'Best University', 'Spectator', 40, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/23/2025 01:53 AM', 'Stadium F', 'Best University', 'Spectator', 31, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/13/2025 04:13 PM', 'Stade de France', 'Morning Gala', 'Participant', 63, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 08:19 PM', 'Arena B', 'Cool Training 2025', 'Spectator', 58, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/05/2025 05:26 PM', 'Zenith', 'Cool Training 2025', 'Spectator', 47, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/13/2025 11:10 AM', 'Parc des princes', 'European Step', 'Spectator', 42, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 09:08 AM', 'Palais des Congrès', 'World of Experts', 'Spectator', 24, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/10/2025 01:57 AM', 'Park C', 'Best University', 'Participant', 56, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/13/2025 09:59 AM', 'Accor Arena', 'Morning Gala', 'Spectator', 19, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/23/2025 04:25 AM', 'Palais des Congrès', 'Epic Battle', 'Spectator', 34, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/28/2025 11:57 AM', 'Arena G', 'Amazing stuff', 'Participant', 68, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/18/2025 09:01 PM', 'Stade de France', 'Extravaganza', 'Participant', 5, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/19/2025 09:26 AM', 'Pool D', 'World Contest', 'Spectator', 60, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/27/2025 04:27 PM', 'Palais des Congrès', 'World of Experts', 'Spectator', 89, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/22/2025 10:22 PM', 'Pool D', 'Extravaganza', 'Participant', 2, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/10/2025 04:11 PM', 'Accor Arena', 'Course', 'Spectator', 72, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/03/2025 04:31 PM', 'Parc des princes', 'Enthusiasts', 'Spectator', 26, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/01/2025 03:46 AM', 'Parc des princes', 'Course', 'Participant', 3, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/07/2025 04:16 AM', 'Palais des Congrès', 'World of Experts', 'Participant', 73, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 05:56 PM', 'Parc des princes', 'Splash', 'Spectator', 49, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/03/2025 08:26 AM', 'Zenith', 'World Contest', 'Participant', 15, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/04/2025 02:36 AM', 'Pool D', 'World of Experts', 'Spectator', 28, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/01/2025 11:03 PM', 'Park C', 'Best University', 'Participant', 89, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/11/2025 07:55 PM', 'Accor Arena', 'Tournament', 'Spectator', 47, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/09/2025 07:35 AM', 'Court E', 'Morning Gala', 'Participant', 14, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/20/2025 09:51 PM', 'Cnit', 'Epic Battle', 'Spectator', 11, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/07/2025 05:10 AM', 'Stade de France', 'Epic Battle', 'Spectator', 27, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/18/2025 12:10 PM', 'Zenith', 'Tournament', 'Spectator', 91, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/19/2025 11:59 PM', 'Stade de France', 'Fantasy 2025', 'Spectator', 21, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/11/2025 03:22 AM', 'Parc des princes', 'Course', 'Participant', 35, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/31/2025 09:01 AM', 'Stadium A', 'Amazing stuff', 'Spectator', 98, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/02/2025 06:11 AM', 'Arena G', 'Morning Gala', 'Spectator', 100, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/06/2025 03:43 AM', 'Arena B', 'Amazing stuff', 'Spectator', 76, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/29/2025 11:31 AM', 'Court E', 'Amazing stuff', 'Spectator', 43, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/18/2025 08:58 PM', 'Pool D', 'European Step', 'Spectator', 41, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/16/2025 07:41 PM', 'Court E', 'Cool Training 2025', 'Spectator', 93, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/14/2025 03:36 PM', 'Parc des princes', 'Fantasy 2025', 'Spectator', 65, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/09/2025 08:44 PM', 'Court E', 'Extravaganza', 'Spectator', 99, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/04/2025 12:24 PM', 'Court E', 'Best University', 'Spectator', 2, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/13/2025 03:22 PM', 'Cnit', 'Morning Gala', 'Participant', 78, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/21/2025 04:47 AM', 'Stade de France', 'Showcase', 'Spectator', 89, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/05/2025 09:32 AM', 'Stade de France', 'Enthusiasts', 'Spectator', 98, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/08/2025 06:38 AM', 'Accor Arena', 'European Step', 'Participant', 82, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/12/2025 09:04 AM', 'Pool D', 'Fantasy 2025', 'Participant', 59, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/23/2025 07:45 PM', 'Parc des princes', 'Tournament', 'Participant', 41, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/02/2025 09:34 AM', 'Arena G', 'Extravaganza', 'Spectator', 47, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/07/2025 04:51 PM', 'Stadium F', 'World Contest', 'Spectator', 41, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('07/06/2025 11:10 AM', 'Parc des princes', 'Cool Training 2025', 'Spectator', 85, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/06/2025 07:07 AM', 'Zenith', 'Tournament', 'Spectator', 71, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('08/13/2025 02:08 AM', 'Stadium A', 'Enthusiasts', 'Spectator', 18, 'Fitness');
