-- Création de la table
DROP TABLE IF EXISTS events;
CREATE TABLE events (
    id SERIAL PRIMARY KEY,
    event_date TIMESTAMP,
    location TEXT,
    name TEXT,
    participation_type TEXT,
    popularity_score INTEGER,
    sport_type TEXT
);

-- Insertion des données
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-21 01:48:38', 'Arena B', 'Showcase', 'Spectator', 5, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-24 07:15:47', 'Palais des Congrès', 'Enthusiasts', 'Spectator', 75, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-04 02:50:03', 'Stade de France', 'World Contest', 'Participant', 46, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-05 19:32:03', 'Zenith', 'Amazing stuff', 'Participant', 10, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-24 13:22:03', 'Stade de France', 'Tournament', 'Spectator', 68, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-12 20:01:18', 'Arena G', 'World Contest', 'Spectator', 100, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-01 14:28:08', 'Cnit', 'Tournament', 'Spectator', 56, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-05 00:29:40', 'Stadium A', 'Tournament', 'Spectator', 17, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-09 10:04:03', 'Cnit', 'Cool Training 2025', 'Spectator', 8, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-06 23:58:57', 'Stadium A', 'Tournament', 'Spectator', 2, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-09 04:01:02', 'Accor Arena', 'World Contest', 'Spectator', 33, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-10 18:52:34', 'Court E', 'Best University', 'Spectator', 33, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-08 00:01:08', 'Stadium A', 'Tournament', 'Spectator', 60, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-14 12:02:36', 'Court E', 'Morning Gala', 'Spectator', 61, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-01 07:21:14', 'Stadium A', 'European Step', 'Spectator', 61, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-28 05:47:02', 'Pool D', 'Course', 'Spectator', 79, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-05 06:21:26', 'Arena B', 'World Contest', 'Spectator', 52, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-12 02:18:37', 'Stadium F', 'Tournament', 'Participant', 9, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-05 14:51:55', 'Stadium F', 'World Contest', 'Participant', 67, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-25 10:56:59', 'Arena G', 'Best University', 'Participant', 43, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-07 21:00:58', 'Stade de France', 'Fantasy 2025', 'Participant', 19, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-03 04:10:32', 'Court E', 'Splash', 'Spectator', 70, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-21 12:04:27', 'Cnit', 'Cool Training 2025', 'Spectator', 93, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-18 02:57:07', 'Park C', 'World of Experts', 'Spectator', 32, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-07 07:45:08', 'Stadium F', 'Epic Battle', 'Spectator', 60, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-14 09:05:27', 'Arena B', 'Epic Battle', 'Spectator', 63, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-05 19:43:39', 'Stade de France', 'Tournament', 'Spectator', 68, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-29 08:01:24', 'Palais des Congrès', 'Morning Gala', 'Spectator', 62, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-24 02:28:30', 'Parc des princes', 'Tournament', 'Participant', 30, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-07 02:51:12', 'Palais des Congrès', 'Tournament', 'Spectator', 44, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-18 19:45:14', 'Palais des Congrès', 'Enthusiasts', 'Spectator', 57, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-02 18:28:24', 'Stade de France', 'World of Experts', 'Spectator', 19, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-31 09:12:43', 'Stade de France', 'Tournament', 'Spectator', 92, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-05 14:51:25', 'Stade de France', 'Splash', 'Spectator', 97, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-18 19:29:05', 'Stadium A', 'Tournament', 'Spectator', 15, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-18 23:22:00', 'Accor Arena', 'Enthusiasts', 'Spectator', 5, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-04 03:11:54', 'Stadium F', 'World of Experts', 'Spectator', 36, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-22 20:20:05', 'Cnit', 'Cool Training 2025', 'Participant', 2, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-26 06:29:22', 'Palais des Congrès', 'Best University', 'Participant', 68, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-03 20:08:35', 'Zenith', 'Showcase', 'Spectator', 93, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-06 09:58:37', 'Arena G', 'Amazing stuff', 'Participant', 26, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-10 02:29:32', 'Court E', 'Best University', 'Spectator', 72, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-23 21:08:01', 'Arena B', 'Epic Battle', 'Spectator', 75, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-05 20:03:03', 'Zenith', 'Fantasy 2025', 'Participant', 5, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-08 20:27:40', 'Stade de France', 'Enthusiasts', 'Participant', 97, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-09 11:07:56', 'Court E', 'Tournament', 'Spectator', 55, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-29 16:00:21', 'Parc des princes', 'Showcase', 'Participant', 10, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-14 11:09:33', 'Stadium F', 'Fantasy 2025', 'Participant', 87, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-27 12:27:23', 'Stadium A', 'Cool Training 2025', 'Spectator', 11, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-06 23:14:14', 'Parc des princes', 'Epic Battle', 'Participant', 29, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-08 15:12:53', 'Cnit', 'Tournament', 'Participant', 32, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-26 18:19:12', 'Accor Arena', 'Tournament', 'Spectator', 51, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-13 06:01:25', 'Stade de France', 'Cool Training 2025', 'Spectator', 86, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-08 06:03:41', 'Palais des Congrès', 'World Contest', 'Spectator', 21, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-08 10:36:07', 'Pool D', 'Splash', 'Participant', 28, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-03 10:17:04', 'Stadium F', 'Tournament', 'Participant', 2, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-05 01:57:45', 'Pool D', 'Course', 'Participant', 100, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-03 12:53:20', 'Zenith', 'Course', 'Participant', 35, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-01 15:03:09', 'Court E', 'Showcase', 'Participant', 9, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-03 06:14:10', 'Accor Arena', 'Course', 'Participant', 6, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-28 09:16:50', 'Arena B', 'Best University', 'Participant', 81, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-06 17:46:10', 'Court E', 'Fantasy 2025', 'Participant', 40, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-07 08:37:09', 'Parc des princes', 'Course', 'Participant', 58, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-11 03:18:07', 'Cnit', 'World of Experts', 'Participant', 96, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-25 04:13:44', 'Palais des Congrès', 'Showcase', 'Spectator', 81, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-26 20:25:59', 'Accor Arena', 'Splash', 'Spectator', 32, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-14 04:00:14', 'Park C', 'Course', 'Spectator', 46, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-31 08:42:21', 'Zenith', 'World Contest', 'Participant', 12, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-26 00:13:42', 'Accor Arena', 'Best University', 'Spectator', 10, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-01 05:15:55', 'Zenith', 'Course', 'Participant', 52, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-12 12:05:12', 'Stadium A', 'Fantasy 2025', 'Spectator', 58, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-31 08:21:18', 'Stadium F', 'Tournament', 'Participant', 73, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-01 23:37:10', 'Stade de France', 'Morning Gala', 'Participant', 13, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-26 03:35:47', 'Zenith', 'Epic Battle', 'Participant', 43, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-04 17:39:46', 'Arena B', 'World of Experts', 'Spectator', 32, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-21 18:31:49', 'Parc des princes', 'Splash', 'Participant', 87, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-08 23:44:07', 'Cnit', 'Cool Training 2025', 'Participant', 93, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-23 09:27:58', 'Arena G', 'Amazing stuff', 'Spectator', 25, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-10 21:22:50', 'Arena B', 'Best University', 'Participant', 60, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-13 16:06:57', 'Stade de France', 'Enthusiasts', 'Spectator', 64, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-10 14:53:39', 'Cnit', 'Cool Training 2025', 'Spectator', 80, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-16 13:24:05', 'Cnit', 'Splash', 'Spectator', 86, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-21 09:40:50', 'Stade de France', 'Cool Training 2025', 'Participant', 80, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-04 01:17:00', 'Parc des princes', 'Extravaganza', 'Participant', 85, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-08 18:35:20', 'Pool D', 'Enthusiasts', 'Participant', 97, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-17 05:03:43', 'Stadium F', 'Enthusiasts', 'Spectator', 64, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-11 08:11:53', 'Pool D', 'Tournament', 'Spectator', 58, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-13 13:12:14', 'Park C', 'Enthusiasts', 'Participant', 50, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-06 03:00:23', 'Parc des princes', 'Splash', 'Spectator', 97, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-13 12:58:45', 'Parc des princes', 'Enthusiasts', 'Participant', 40, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-31 18:58:01', 'Accor Arena', 'Fantasy 2025', 'Participant', 8, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-22 01:29:16', 'Accor Arena', 'World Contest', 'Spectator', 42, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-08 04:29:35', 'Arena B', 'Morning Gala', 'Spectator', 91, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-07 02:11:46', 'Park C', 'Tournament', 'Spectator', 86, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-16 13:20:30', 'Stadium A', 'World of Experts', 'Spectator', 31, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-06 14:29:20', 'Park C', 'Epic Battle', 'Spectator', 88, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-14 15:28:33', 'Zenith', 'World of Experts', 'Participant', 18, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-09 13:03:35', 'Pool D', 'Morning Gala', 'Participant', 77, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-06 12:34:08', 'Accor Arena', 'Tournament', 'Participant', 19, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-08 15:35:45', 'Arena G', 'Best University', 'Participant', 5, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-24 23:35:29', 'Palais des Congrès', 'Tournament', 'Participant', 71, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-31 17:43:02', 'Stadium A', 'Splash', 'Participant', 86, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-16 00:49:41', 'Arena B', 'Enthusiasts', 'Spectator', 71, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-18 09:14:39', 'Cnit', 'Showcase', 'Participant', 81, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-23 22:35:31', 'Pool D', 'Best University', 'Spectator', 59, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-09 07:38:47', 'Parc des princes', 'World Contest', 'Spectator', 80, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-18 06:16:42', 'Stadium F', 'Fantasy 2025', 'Participant', 59, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-05 08:14:41', 'Park C', 'Splash', 'Participant', 61, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-06 05:36:05', 'Arena G', 'Best University', 'Spectator', 93, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-14 08:15:18', 'Zenith', 'World Contest', 'Spectator', 86, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-02 19:37:01', 'Cnit', 'Cool Training 2025', 'Participant', 79, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-01 23:15:49', 'Accor Arena', 'European Step', 'Participant', 91, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-05 17:41:10', 'Accor Arena', 'Extravaganza', 'Participant', 41, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-13 10:26:01', 'Court E', 'Fantasy 2025', 'Participant', 56, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-31 02:46:50', 'Pool D', 'Enthusiasts', 'Spectator', 32, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-10 23:59:20', 'Stade de France', 'European Step', 'Participant', 70, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-25 23:47:55', 'Zenith', 'Fantasy 2025', 'Spectator', 69, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-06 20:18:28', 'Stadium F', 'Course', 'Spectator', 53, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-26 10:50:32', 'Palais des Congrès', 'Morning Gala', 'Spectator', 16, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-25 18:50:30', 'Cnit', 'World of Experts', 'Spectator', 73, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-31 11:18:03', 'Zenith', 'Splash', 'Participant', 6, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-28 01:45:04', 'Zenith', 'Morning Gala', 'Participant', 84, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-06 07:01:21', 'Accor Arena', 'Course', 'Participant', 3, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-14 04:02:35', 'Stadium A', 'European Step', 'Participant', 21, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-02 13:03:07', 'Cnit', 'Morning Gala', 'Spectator', 3, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-25 12:13:11', 'Stadium A', 'Tournament', 'Participant', 63, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-25 22:33:18', 'Court E', 'Morning Gala', 'Spectator', 0, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-29 18:13:44', 'Parc des princes', 'European Step', 'Spectator', 68, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-13 07:10:22', 'Arena B', 'Best University', 'Participant', 84, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-08 19:58:20', 'Accor Arena', 'Showcase', 'Participant', 52, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-04 11:00:42', 'Stadium A', 'Epic Battle', 'Participant', 91, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-08 10:45:27', 'Pool D', 'Tournament', 'Participant', 7, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-16 09:29:50', 'Arena G', 'Amazing stuff', 'Spectator', 31, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-21 03:43:59', 'Accor Arena', 'Tournament', 'Participant', 5, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-25 04:37:37', 'Pool D', 'World of Experts', 'Participant', 73, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-14 04:16:55', 'Court E', 'Course', 'Spectator', 50, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-11 16:45:21', 'Arena B', 'World Contest', 'Participant', 63, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-09 06:57:33', 'Court E', 'Course', 'Participant', 68, 'Badminton');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-19 07:48:00', 'Pool D', 'Epic Battle', 'Participant', 71, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-01 02:33:17', 'Stadium A', 'Fantasy 2025', 'Participant', 43, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-12 00:46:35', 'Arena B', 'Cool Training 2025', 'Participant', 33, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-08 00:15:46', 'Court E', 'World Contest', 'Spectator', 91, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-04 07:31:24', 'Zenith', 'European Step', 'Spectator', 77, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-07 03:55:32', 'Cnit', 'Enthusiasts', 'Participant', 23, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-06 03:32:16', 'Stadium A', 'Tournament', 'Participant', 13, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-08 01:44:22', 'Palais des Congrès', 'Fantasy 2025', 'Spectator', 46, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-29 02:17:39', 'Parc des princes', 'Tournament', 'Spectator', 42, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-14 11:58:57', 'Stadium A', 'Enthusiasts', 'Participant', 70, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-07 14:17:56', 'Parc des princes', 'Tournament', 'Spectator', 45, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-31 01:20:42', 'Cnit', 'Morning Gala', 'Participant', 38, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-01 02:52:46', 'Stadium F', 'Epic Battle', 'Participant', 9, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-08 05:43:07', 'Court E', 'World of Experts', 'Spectator', 5, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-06 02:06:37', 'Park C', 'Best University', 'Spectator', 51, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-12 18:47:57', 'Park C', 'Best University', 'Spectator', 34, 'Football');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-09 03:58:57', 'Parc des princes', 'Best University', 'Participant', 19, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-10 10:01:02', 'Stade de France', 'World of Experts', 'Participant', 69, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-15 03:56:07', 'Palais des Congrès', 'World of Experts', 'Participant', 47, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-12 20:52:05', 'Stadium F', 'World Contest', 'Spectator', 68, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-17 12:22:38', 'Pool D', 'Extravaganza', 'Participant', 77, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-02 05:56:08', 'Park C', 'Fantasy 2025', 'Participant', 31, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-02 22:33:13', 'Stadium F', 'Tournament', 'Participant', 84, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-03 04:09:50', 'Palais des Congrès', 'Fantasy 2025', 'Spectator', 99, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-22 06:35:47', 'Court E', 'Best University', 'Participant', 45, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-03 06:02:54', 'Stade de France', 'Splash', 'Spectator', 59, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-06 19:22:54', 'Court E', 'Epic Battle', 'Spectator', 23, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-07 03:07:49', 'Cnit', 'Tournament', 'Participant', 11, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-08 19:13:16', 'Pool D', 'Tournament', 'Participant', 15, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-25 15:42:21', 'Arena G', 'Tournament', 'Participant', 53, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-22 11:34:52', 'Pool D', 'Course', 'Participant', 51, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-07 09:49:10', 'Parc des princes', 'Showcase', 'Spectator', 61, 'Dance');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-14 23:46:16', 'Arena G', 'Splash', 'Participant', 49, 'Yoga');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-08 03:26:12', 'Stadium A', 'Amazing stuff', 'Participant', 37, 'Zumba');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-23 23:15:18', 'Zenith', 'Epic Battle', 'Spectator', 21, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-05 03:30:13', 'Arena G', 'Enthusiasts', 'Participant', 2, 'Tennis');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-13 23:54:13', 'Pool D', 'Tournament', 'Spectator', 61, 'Swimming');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-09 20:00:32', 'Arena B', 'Best University', 'Spectator', 49, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-07 03:07:43', 'Cnit', 'Extravaganza', 'Participant', 87, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-14 18:15:54', 'Stade de France', 'European Step', 'Spectator', 46, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-12 14:36:45', 'Stadium F', 'Epic Battle', 'Spectator', 84, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-13 15:41:42', 'Stadium F', 'Course', 'Participant', 10, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-14 20:24:49', 'Arena G', 'Fantasy 2025', 'Participant', 41, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-11 13:07:34', 'Palais des Congrès', 'Amazing stuff', 'Spectator', 77, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-28 17:54:30', 'Parc des princes', 'Splash', 'Spectator', 10, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-26 22:18:11', 'Accor Arena', 'Enthusiasts', 'Spectator', 99, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-20 18:17:20', 'Stadium A', 'World Contest', 'Participant', 0, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-04 01:01:14', 'Court E', 'Amazing stuff', 'Participant', 82, 'Bodybuilding');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-26 19:20:25', 'Court E', 'Tournament', 'Participant', 79, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-16 22:30:56', 'Zenith', 'World of Experts', 'Spectator', 73, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-04 03:55:17', 'Stadium A', 'Enthusiasts', 'Spectator', 68, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-22 17:23:44', 'Stadium A', 'Showcase', 'Spectator', 94, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-18 15:01:15', 'Cnit', 'Showcase', 'Participant', 2, 'Judo');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-14 21:20:11', 'Accor Arena', 'Showcase', 'Spectator', 59, 'Running');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-01 17:53:54', 'Court E', 'Splash', 'Participant', 46, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-12 02:34:54', 'Parc des princes', 'Extravaganza', 'Spectator', 99, 'Basketball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-07 06:32:09', 'Stadium A', 'World Contest', 'Spectator', 35, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-07 12:25:03', 'Arena G', 'Tournament', 'Spectator', 9, 'Pilates');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-08-01 20:11:55', 'Pool D', 'Best University', 'Spectator', 60, 'Volleyball');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-05 03:23:29', 'Park C', 'Morning Gala', 'Spectator', 70, 'Fitness');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-07 03:39:44', 'Court E', 'Fantasy 2025', 'Spectator', 100, 'Golf');
insert into events (event_date, location, name, participation_type, popularity_score, sport_type) values ('2025-07-25 00:13:17', 'Arena G', 'Course', 'Participant', 47, 'Pilates');
